---

- hosts: all
  become: true
  become_user: root
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian"] and ansible_distribution_major_version == "10"

  - name: install apache2 package
    apt: 
      name: apache2
      state: absent
    when: ansible_distribution in ["Debian"] and ansible_distribution_major_version == "10"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian"] and ansible_distribution_major_version == "10"